bot_prefix: "neil "
token: "API_TOKEN"
application_id: "APPLICATION_ID"
asset_dir: "./assets"
booty_cmd_channel_id: 697214870520856709
owners:
  - 200062707540557825
blacklist:
main_color: 0xD75BF4
error: 0xE02B2B
success: 0x42F56C
warning: 0xF59E42
info: 0x4299F5